apiVersion: v1
kind: Service
metadata:
  name: noppflow
  labels:
    app: noppflow
spec:
  type: ClusterIP
  selector:
    app: noppflow
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
